# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1759d76687af0475d8d9b097cad391682d7d63e51b6af71210b189b170963670b115ba88f6d5bdb280b485e027e603e5d88db8f65af320189a516ab73a5a2ba2

test:
  secret_key_base: 828e3c3a4c08deeaa6fce255778941f8acc7def8093395bdb5998f1c7011308e6d1c11e7ef667962ddf93409f57dda11fdcd05170e84befa93da67e546ad2adb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
